//
//  AllPromotionsPresenter.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 07/05/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PromotionGroupPresentationLogic
{
    func presentAllPromotions(response: PromotionGroup.GetPromotions.Response)
}

class PromotionGroupPresenter: PromotionGroupPresentationLogic
{
    weak var viewController: PromotionGroupDisplayLogic?
    
    func presentAllPromotions(response: PromotionGroup.GetPromotions.Response)
    {
        let viewModel = PromotionGroup.GetPromotions.ViewModel(promotionGroup: response.promotionGroup, promotions: response.promotions)
        viewController?.displayPromotions(viewModel: viewModel)
    }
}
