//
//  HomeRouter.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 27/02/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic
{
    func routeToShowPromotion(segue: UIStoryboardSegue?)
    func routeToShowProduct(segue: UIStoryboardSegue?)
    func routeToStore(segue: UIStoryboardSegue?)
    func routeToShowList(segue: UIStoryboardSegue?)
}

protocol HomeDataPassing
{
    var dataStore: HomeDataStore? { get }
    
    var selectedList: ListModel? { get set }
    var selectedProductID: Int? { get set }
    var selectedPromotionID: Int? { get set }
    var selectedStoreID: Int? { get set }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing
{
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?
    
    var selectedList: ListModel?
    
    var selectedProductID: Int?
    var selectedPromotionID: Int?
    var selectedStoreID: Int?
    
    // MARK: Routing
    
    func routeToShowList(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! ShowListViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowList(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "ShowListViewController") as! ShowListViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowList(source: dataStore!, destination: &destinationDS)
            navigateToShowList(source: viewController!, destination: destinationVC)
        }
    }
    
    func routeToStore(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! StoreViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToStore(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "StoreViewController") as! StoreViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToStore(source: dataStore!, destination: &destinationDS)
            navigateToStore(source: viewController!, destination: destinationVC)
        }
    }
    
    func routeToShowProduct(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! ShowProductViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowProduct(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "ShowProductViewController") as! ShowProductViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowProduct(source: dataStore!, destination: &destinationDS)
            navigateToShowProduct(source: viewController!, destination: destinationVC)
        }
    }
    
    func routeToShowPromotion(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! ShowPromotionViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowPromotion(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "ShowPromotionViewController") as! ShowPromotionViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowPromotion(source: dataStore!, destination: &destinationDS)
            navigateToShowPromotion(source: viewController!, destination: destinationVC)
        }
    }
    
    //    MARK: Navigation
    
    func navigateToShowList(source: HomeViewController, destination: ShowListViewController)
    {
        source.show(destination, sender: nil)
    }
    
    func navigateToShowProduct(source: HomeViewController, destination: ShowProductViewController)
    {
        source.show(destination, sender: nil)
    }
    
    func navigateToShowPromotion(source: HomeViewController, destination: ShowPromotionViewController)
    {
        source.show(destination, sender: nil)
    }
    
    func navigateToStore(source: HomeViewController, destination: StoreViewController)
    {
        source.show(destination, sender: nil)
    }
    
    //    MARK: Passing data
    
    func passDataToShowList(source: HomeDataStore, destination: inout ShowListDataStore)
    {
        destination.list = selectedList
    }
    
    func passDataToShowProduct(source: HomeDataStore, destination: inout ShowProductDataStore)
    {
        destination.productID = selectedProductID!
    }
    
    func passDataToShowPromotion(source: HomeDataStore, destination: inout ShowPromotionDataStore)
    {
        destination.promotionID = selectedPromotionID!
    }
    
    func passDataToStore(source: HomeDataStore, destination: inout StoreDataStore)
    {
        destination.storeID = selectedStoreID!
    }
}
