//
//  EditPasswordViewController.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 03/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditPasswordDisplayLogic: AnyObject
{
    func displayPasswordUpdated(viewModel: EditPassword.UpdatePassword.ViewModel)
}

class EditPasswordViewController: UIViewController, EditPasswordDisplayLogic
{
    var interactor: EditPasswordBusinessLogic?
    var router: (NSObjectProtocol & EditPasswordRoutingLogic & EditPasswordDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = EditPasswordInteractor()
        let presenter = EditPasswordPresenter()
        let router = EditPasswordRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        openKeyboardOnTextField()
        setupTextFieldDelegates()
    }
    
    let spinner: SpinnerViewController = SpinnerViewController()
    
    @IBOutlet var currentPasswordTextField: UITextField!
    @IBOutlet var newPasswordTextField: UITextField!
    @IBOutlet var confirmPasswordTextField: UITextField!
    
    func updatePassword()
    {
        startLoading()
        submitForm()
    }
    
    func displayPasswordUpdated(viewModel: EditPassword.UpdatePassword.ViewModel)
    {
        stopLoading()
        
        if let error = viewModel.error {
            showRightBarButton()
            showError(title: "Update Error", error: error)
        } else {
            router?.routeToSettings(segue: nil)
        }
    }
    
    
    func submitForm(){
        hideRightBarButton()
        dismissKeyboard()
        
        let currentPassword = currentPasswordTextField.text ?? ""
        let newPassword = newPasswordTextField.text ?? ""
        let confirmPassword = confirmPasswordTextField.text ?? ""
        
        let request = EditPassword.UpdatePassword.Request(
            currentPassword: currentPassword, newPassword: newPassword, confirmPassword: confirmPassword
        )
        
        interactor?.updatePassword(request: request)
    }

}

extension EditPasswordViewController {
    @IBAction func saveButtonPressed(_ sender: Any) {
        updatePassword()
    }
}

extension EditPasswordViewController {
    func dismissKeyboard(){
        view.endEditing(true)
    }
    
    func openKeyboardOnTextField(){
        currentPasswordTextField.becomeFirstResponder()
    }
    
    func hideRightBarButton(){
        navigationItem.rightBarButtonItem?.isEnabled = false
    }
    
    func showRightBarButton(){
        navigationItem.rightBarButtonItem?.isEnabled = true
    }
}

extension EditPasswordViewController: UITextFieldDelegate {
    
    private func setupTextFieldDelegates(){
        let textFields: [UITextField]! = [currentPasswordTextField, newPasswordTextField, confirmPasswordTextField]
        
        for field in textFields {
            field.delegate = self
        }
    }
    
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        let textFields: [UITextField]! = [currentPasswordTextField, newPasswordTextField, confirmPasswordTextField]
        
        textField.resignFirstResponder()
        
        if let index = textFields.firstIndex(of: textField) {
            if index < textFields.count - 1 {
                let nextTextField = textFields[index + 1]
                nextTextField.becomeFirstResponder()
            } else {
                startLoading()
                dismissKeyboard()
                submitForm()
            }
        }
        
        return true
    }
}

extension EditPasswordViewController {
    func startLoading() {
        addChild(spinner)
        spinner.view.frame = view.frame
        view.addSubview(spinner.view)
        spinner.didMove(toParent: self)
    }
    
    func stopLoading(){
        spinner.willMove(toParent: nil)
        spinner.view.removeFromSuperview()
        spinner.removeFromParent()
    }
}
