//
//  ShowReviewsInteractor.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 28/02/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowReviewsBusinessLogic
{
    func getReviews(request: ShowReviews.GetReviews.Request)
}

protocol ShowReviewsDataStore
{
    var productID: Int { get set }
}

class ShowReviewsInteractor: ShowReviewsBusinessLogic, ShowReviewsDataStore
{
    var presenter: ShowReviewsPresentationLogic?
    var reviewWorker: ReviewWorker = ReviewWorker(reviewAPI: ReviewAPI())
    
    var productID: Int = 1
    
    // MARK: Do something
    
    func getReviews(request: ShowReviews.GetReviews.Request)
    {
        reviewWorker.getReviews(productID: productID) { (reviews: [ReviewModel], error: String?) in
            let response = ShowReviews.GetReviews.Response(reviews: reviews, error: error)
            self.presenter?.presentReviews(response: response)
        }
    }
}
