//
//  AllPromotionsRouter.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 07/05/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AllPromotionsRoutingLogic
{
    func routeToPromotionGroup(segue: UIStoryboardSegue?)
}

protocol AllPromotionsDataPassing
{
    var dataStore: AllPromotionsDataStore? { get }
}

class AllPromotionsRouter: NSObject, AllPromotionsRoutingLogic, AllPromotionsDataPassing
{
    weak var viewController: AllPromotionsViewController?
    var dataStore: AllPromotionsDataStore?
    
    // MARK: Routing
    
    func routeToPromotionGroup(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! PromotionGroupViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowPromotion(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "PromotionGroupViewController") as! PromotionGroupViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowPromotion(source: dataStore!, destination: &destinationDS)
            navigateToShowPromotion(source: viewController!, destination: destinationVC)
        }
    }
    
    
    // MARK: Navigation
    
    func navigateToShowPromotion(source: AllPromotionsViewController, destination: PromotionGroupViewController)
    {
        source.show(destination, sender: nil)
    }
    // MARK: Passing data
    
    func passDataToShowPromotion(source: AllPromotionsDataStore, destination: inout PromotionGroupDataStore)
    {
        destination.promotionGroup = source.selectedPromotionGroup
    }
}
