//
//  AllPromotionsInteractor.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 07/05/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AllPromotionsBusinessLogic
{
    func getAllPromotions(request: AllPromotions.GetAllPromotions.Request)
    func setPromotionSelected(promotionGroup: String)
}

protocol AllPromotionsDataStore
{
    var storeTypeID: Int { get set }
    var selectedPromotionGroup: String? { get set }
}

class AllPromotionsInteractor: AllPromotionsBusinessLogic, AllPromotionsDataStore
{
    
    var presenter: AllPromotionsPresentationLogic?
    var promotionWorker = PromotionWorker(promotionAPI: PromotionAPI())

    var storeTypeID: Int = 2
    var selectedPromotionGroup: String? = nil
    
    var userSession: UserSessionWorker = UserSessionWorker()
    
    func getAllPromotions(request: AllPromotions.GetAllPromotions.Request)
    {
        promotionWorker.getAllPromotions(storeTypeID: storeTypeID) { (promotionGroups: [String], error: String?) in
            
            var response = AllPromotions.GetAllPromotions.Response(promotionGroups: promotionGroups, error: error)
        
            if error != nil {
                response.offline = !self.userSession.isOnline()
            }
            
            self.presenter?.presentAllPromotions(response: response)
        }
    }
}

extension AllPromotionsInteractor {
    public func setPromotionSelected(promotionGroup: String){
        self.selectedPromotionGroup = promotionGroup
    }
}
