//
//  ShowProductInteractor.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 27/02/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowProductBusinessLogic
{
    func getProduct(request: ShowProduct.GetProduct.Request)
    func updateFavourite(request: ShowProduct.UpdateFavourite.Request)
    func updateMonitoring(request: ShowProduct.UpdateMonitoring.Request)
}

protocol ShowProductDataStore
{
    var productID: Int { get set }
    var product: ProductModel? { get set }
}

class ShowProductInteractor: ShowProductBusinessLogic, ShowProductDataStore
{
    var presenter: ShowProductPresentationLogic?
    var productWorker: ProductWorker = ProductWorker(productAPI: ProductAPI())
    var favouriteWorker: FavouriteWorker = FavouriteWorker(favouriteAPI: FavouriteAPI())
    
    var productID: Int = 416
    var product: ProductModel?
    
    func getProduct(request: ShowProduct.GetProduct.Request)
    {
        productWorker.getProduct(productID: productID) { (product: ProductModel?, error: String?) in
            self.product = product
            let response = ShowProduct.GetProduct.Response(product: product, error: error)
            self.presenter?.presentProduct(response: response)
        }
    }
    
    func updateFavourite(request: ShowProduct.UpdateFavourite.Request){
        favouriteWorker.updateFavourite(productID: product!.id, favourite: request.favourite) { (error: String?) in
            let response = ShowProduct.UpdateFavourite.Response(error: error)
            self.presenter?.presentFavourite(response: response)
        }
    }
    
    func updateMonitoring(request: ShowProduct.UpdateMonitoring.Request){
        productWorker.updateMonitor(productID: product!.id, monitor: request.monitor) { (error: String?) in
            let response = ShowProduct.UpdateMonitoring.Response(error: error)
            self.presenter?.presentMonitoring(response: response)
        }
    }
}
