//
//  ShowProductInteractor.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 27/02/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowProductBusinessLogic
{
    func getProduct(request: ShowProduct.GetProduct.Request)
}

protocol ShowProductDataStore
{
    var productID: Int { get set }
    var product: ProductModel? { get set }
}

class ShowProductInteractor: ShowProductBusinessLogic, ShowProductDataStore
{
    var presenter: ShowProductPresentationLogic?
    var productWorker: ProductWorker = ProductWorker(productAPI: ProductAPI())
    
    var productID: Int = 416
    var product: ProductModel?
    
    func getProduct(request: ShowProduct.GetProduct.Request)
    {
        productWorker.getProduct(productID: productID) { (product: ProductModel?, error: String?) in
            self.product = product
            let response = ShowProduct.GetProduct.Response(product: product, error: error)
            self.presenter?.presentProduct(response: response)
        }
    }
}
