//
//  ShowProductRouter.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 27/02/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ShowProductRoutingLogic
{
    func routeToShowReviews(segue: UIStoryboardSegue?)
}

protocol ShowProductDataPassing
{
    var dataStore: ShowProductDataStore? { get }
}

class ShowProductRouter: NSObject, ShowProductRoutingLogic, ShowProductDataPassing
{
    weak var viewController: ShowProductViewController?
    var dataStore: ShowProductDataStore?
    
    // MARK: Routing
    
    func routeToShowReviews(segue: UIStoryboardSegue?)
    {
      if let segue = segue {
        let destinationVC = segue.destination as! ShowReviewsViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
      } else {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "ShowReviewsViewController") as! ShowReviewsViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        navigateToSomewhere(source: viewController!, destination: destinationVC)
      }
    }
    
    // MARK: Navigation
    
    func navigateToSomewhere(source: ShowProductViewController, destination: ShowReviewsViewController)
    {
      source.show(destination, sender: nil)
    }
    
    // MARK: - Passing Data
    func passDataToSomewhere(source: ShowProductDataStore, destination: inout ShowReviewsDataStore)
    {
        destination.productID = source.productID
    }
}
