//
//  EditStoreModels.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 07/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum EditStore
{
    enum GetSupermarketChains
    {
        struct Request
        {
        }
        
        struct Response
        {
            var supermarketChains: [SupermarketChainModel]
            var selectedsupermarketChainID: Int
        }
        
        struct ViewModel
        {
            var supermarketChains: [SupermarketChainModel]
            var selectedsupermarketChainID: Int
        }
    }
    
    enum UpdateStore
    {
        struct Request
        {
            var supermarketChain: SupermarketChainModel
        }
        
        struct Response
        {
            var error: String?
        }
        
        struct ViewModel
        {
            var error: String?
        }
    }
}
