//
//  EditStorePresenter.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 07/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditStorePresentationLogic
{
    func presentUpdatedStore(response: EditStore.UpdateStore.Response)
    func presentSupermarketChains(response: EditStore.GetSupermarketChains.Response)
}

class EditStorePresenter: EditStorePresentationLogic
{
    weak var viewController: EditStoreDisplayLogic?
    
    func presentSupermarketChains(response: EditStore.GetSupermarketChains.Response) {
        let viewModel = EditStore.GetSupermarketChains.ViewModel(supermarketChains: response.supermarketChains, selectedsupermarketChainID: response.selectedsupermarketChainID)
        viewController?.displaySupermarketChains(viewModel: viewModel)
    }
    
    func presentUpdatedStore(response: EditStore.UpdateStore.Response){
        let viewModel = EditStore.UpdateStore.ViewModel(error: response.error)
        viewController?.displayUpdatedStore(viewModel: viewModel)
    }
}
