//
//  EditStoreViewController.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 07/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditStoreDisplayLogic: AnyObject
{
    func displayUpdatedStore(viewModel: EditStore.UpdateStore.ViewModel)
}

class EditStoreViewController: UIViewController, EditStoreDisplayLogic
{
    var interactor: EditStoreBusinessLogic?
    var router: (NSObjectProtocol & EditStoreRoutingLogic & EditStoreDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = EditStoreInteractor()
        let presenter = EditStorePresenter()
        let router = EditStoreRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
    }
    
    let spinner: SpinnerViewController = SpinnerViewController()
    
    var userSession: UserSessionWorker = UserSessionWorker()
    var loggedIn: Bool {
        return userSession.isLoggedIn()
    }
    
    func displayUpdatedStore(viewModel: EditStore.UpdateStore.ViewModel)
    {
        stopLoading()
        
        if loggedIn, let error = viewModel.error {
            showError(title: "Store Change Error", error: error)
        } else {
            router?.routeToSettings(segue: nil)
        }
    }

}

extension EditStoreViewController {
    @IBAction func superstoreButtonPressed(_ sender: Any) {
        startLoading()
        
        let request = EditStore.UpdateStore.Request(storeTypeID: 2)
        interactor?.updateStore(request: request)
    }
    
    @IBAction func asdaButtonPressed(_ sender: Any) {
        startLoading()
        
        let request = EditStore.UpdateStore.Request(storeTypeID: 1)
        interactor?.updateStore(request: request)
    }
}

extension EditStoreViewController {
    func startLoading() {
        addChild(spinner)
        spinner.view.frame = view.frame
        view.addSubview(spinner.view)
        spinner.didMove(toParent: self)
    }
    
    func stopLoading(){
        spinner.willMove(toParent: nil)
        spinner.view.removeFromSuperview()
        spinner.removeFromParent()
    }
}
