//
//  EditStoreInteractor.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 07/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditStoreBusinessLogic
{
    func updateStore(request: EditStore.UpdateStore.Request)
    func getStoreTypes(request: EditStore.GetStoreTypes.Request)
}

protocol EditStoreDataStore
{
    //var name: String { get set }
}

class EditStoreInteractor: EditStoreBusinessLogic, EditStoreDataStore
{
    var presenter: EditStorePresentationLogic?
    
    var userSessionWorker: UserSessionWorker = UserSessionWorker()
    var userWorker: UserSettingsWorker = UserSettingsWorker(userStore: UserRealmStore())
    
    var storeTypeWorker: StoreTypeWorker = StoreTypeWorker()
    
    func getStoreTypes(request: EditStore.GetStoreTypes.Request){
        let storeTypes = storeTypeWorker.getStoreTypes()
        
        let selectedStoreTypeID: Int = storeTypeWorker.getSelectedStoreType().id
        
        let response = EditStore.GetStoreTypes.Response(storeTypes: storeTypes, selectedStoreTypeID: selectedStoreTypeID)
        presenter?.presentStoreTypes(response: response)
    }
    
    func updateStore(request: EditStore.UpdateStore.Request)
    {
        let storeTypeID = request.storeType.id
        
        let loggedIn: Bool = userSessionWorker.isLoggedIn()
        
        userWorker.updateStore(storeTypeID: storeTypeID, loggedIn: loggedIn) { (error: String?) in
            let response = EditStore.UpdateStore.Response(error: error)
            self.presenter?.presentUpdatedStore(response: response)
        }
    }
}
