//
//  EditListPresenter.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 04/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditListPresentationLogic
{
    func presentList(response: EditList.GetList.Response)
    func presentListRestarted(response: EditList.RestartList.Response)
    func presentListUpdated(response: EditList.UpdateList.Response)
}

class EditListPresenter: EditListPresentationLogic
{
    weak var viewController: EditListDisplayLogic?
    
    func presentList(response: EditList.GetList.Response)
    {
        let viewModel = EditList.GetList.ViewModel(name: response.name, storeTypeID: response.storeTypeID)
        viewController?.displayList(viewModel: viewModel)
    }
    
    func presentListUpdated(response: EditList.UpdateList.Response){
        let viewModel = EditList.UpdateList.ViewModel(error: response.error)
        viewController?.displayListUpdated(viewModel: viewModel)
    }
    
    func presentListRestarted(response: EditList.RestartList.Response){
        let viewModel = EditList.RestartList.ViewModel(error: response.error)
        viewController?.displayListRestarted(viewModel: viewModel)
    }
}
