//
//  EditNamePresenter.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 03/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditNamePresentationLogic
{
    func presentName(response: EditName.GetName.Response)
    func presentNameUpdated(response: EditName.UpdateName.Response)
}

class EditNamePresenter: EditNamePresentationLogic
{
    weak var viewController: EditNameDisplayLogic?

    func presentName(response: EditName.GetName.Response)
    {
        let viewModel = EditName.GetName.ViewModel(name: response.name)
        viewController?.displayName(viewModel: viewModel)
    }
    
    func presentNameUpdated(response: EditName.UpdateName.Response)
    {
        let viewModel = EditName.UpdateName.ViewModel(error: response.error)
        viewController?.displayNameUpdated(viewModel: viewModel)
    }
}
