//
//  SendEmailRouter.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 26/02/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SendEmailRoutingLogic
{
    func routeToVerifyCode(segue: UIStoryboardSegue?)
}

protocol SendEmailDataPassing
{
    var dataStore: SendEmailDataStore? { get }
}

class SendEmailRouter: NSObject, SendEmailRoutingLogic, SendEmailDataPassing
{
    weak var viewController: SendEmailViewController?
    var dataStore: SendEmailDataStore?
    
    // MARK: Routing
    
    func routeToVerifyCode(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! VerifyCodeViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "VerifyCodeViewController") as! VerifyCodeViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
            navigateToSomewhere(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToSomewhere(source: SendEmailViewController, destination: VerifyCodeViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToSomewhere(source: SendEmailDataStore, destination: inout VerifyCodeDataStore)
    {
        destination.email = source.email!
    }
}
