//
//  ShowProductResultsModels.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 02/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ShowProductResults
{
    // MARK: Use cases
    
    enum GetResults
    {
        struct Request
        {
            var page: Int = 1
        }
        struct Response
        {
            var products: [ProductModel]
            var paginate: PaginateResultsModel?
            
            var error: String?
        }
        struct ViewModel
        {
            var products: [ProductModel]
            var paginate: PaginateResultsModel?
            
            var error: String?
        }
    }
    
    
    enum GetListItems
    {
        struct Request
        {
        }
        struct Response
        {
            var listItems: [ListItemModel]
        }
        struct ViewModel
        {
            var listItems: [Int: ListItemModel]
        }
    }
    
    enum CreateListItem {
        struct Request
        {
            var listID: Int
            var productID: Int
            var parentCategoryID: Int
        }
        struct Response
        {
            var listItem: ListItemModel?
            var error: String?
        }
        struct ViewModel
        {
            var listItem: ListItemModel?
            var error: String?
        }
    }
    
    enum UpdateListItem {
        struct Request
        {
            var listID: Int
            var productID: Int
            var quantity: Int
        }
        struct Response
        {
            var error: String?
        }
        struct ViewModel
        {
            var error: String?
        }
    }
}
