//
//  ShowProductResultsInteractor.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 02/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowProductResultsBusinessLogic
{
    func getResults(request: ShowProductResults.GetResults.Request)
}

protocol ShowProductResultsDataStore
{
    var productQueryModel: ProductQueryModel { get set }
}

class ShowProductResultsInteractor: ShowProductResultsBusinessLogic, ShowProductResultsDataStore
{
    var presenter: ShowProductResultsPresentationLogic?
    var searchWorker: SearchWorker = SearchWorker(searchAPI: SearchAPI())
    var productQueryModel: ProductQueryModel = ProductQueryModel(query: "", type: "")
    
    func getResults(request: ShowProductResults.GetResults.Request)
    {
        searchWorker.getProductResults(data: productQueryModel) { (results: ProductResultsModel?, error: String?) in
            let response = ShowProductResults.GetResults.Response(products: results?.products ?? [], error: error)
            self.presenter?.presentResults(response: response)
        }
    }
}
