//
//  ShowIngredientsInteractor.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 28/02/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowIngredientsBusinessLogic
{
  func doSomething(request: ShowIngredients.Something.Request)
}

protocol ShowIngredientsDataStore
{
  //var name: String { get set }
}

class ShowIngredientsInteractor: ShowIngredientsBusinessLogic, ShowIngredientsDataStore
{
  var presenter: ShowIngredientsPresentationLogic?
  var worker: ShowIngredientsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ShowIngredients.Something.Request)
  {
    worker = ShowIngredientsWorker()
    worker?.doSomeWork()
    
    let response = ShowIngredients.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
