//
//  MonitoredProductsModels.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 03/05/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MonitoredProducts
{
    // MARK: Use cases
    
    enum GetMonitoredProducts
    {
        struct Request
        {
        }
        struct Response
        {
            var products: [ProductModel]
            var error: String?
            var offline: Bool = false
        }
        struct ViewModel
        {
            var products: [ProductModel]
            var error: String?
            var offline: Bool = false
        }
    }
    
    enum DeleteMonitoredProduct
    {
        struct Request
        {
            var productID: Int
        }
        struct Response
        {
            var error: String?
        }
        struct ViewModel
        {
            var error: String?
        }
    }
}
