//
//  GrandParentCategoriesPresenter.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 03/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GrandParentCategoriesPresentationLogic
{
  func presentCategories(response: GrandParentCategories.GetCategories.Response)
}

class GrandParentCategoriesPresenter: GrandParentCategoriesPresentationLogic
{
  weak var viewController: GrandParentCategoriesDisplayLogic?
  
  func presentCategories(response: GrandParentCategories.GetCategories.Response)
  {
    var displayedCategories: [GrandParentCategories.GetCategories.ViewModel.DisplayedCategory] = []
    
    for category in response.categories {
        displayedCategories.append(GrandParentCategories.GetCategories.ViewModel.DisplayedCategory(name: category.name))
    }
    
    let viewModel = GrandParentCategories.GetCategories.ViewModel(displayedCategories: displayedCategories, error: response.error, offline: response.offline)
    viewController?.displayCategories(viewModel: viewModel)
  }
}
