//
//  GrandParentCategoriesInteractor.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 03/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GrandParentCategoriesBusinessLogic
{
    func getCategories(request: GrandParentCategories.GetCategories.Request)
    var selectedListID: Int? { get set }
}

protocol GrandParentCategoriesDataStore
{
    var storeTypeID: Int { get set }
    var categories: [GrandParentCategoryModel] { get set }
    var selectedListID: Int? { get set }
}

class GrandParentCategoriesInteractor: GrandParentCategoriesBusinessLogic, GrandParentCategoriesDataStore
{
    var presenter: GrandParentCategoriesPresentationLogic?
    var groceryWorker: GroceryWorker = GroceryWorker(groceryAPI: GroceryAPI())
    
    var selectedListID: Int?
    
    var storeTypeID: Int = 1
    var categories: [GrandParentCategoryModel] = []
    
    // MARK: Do something
    
    func getCategories(request: GrandParentCategories.GetCategories.Request)
    {
        groceryWorker.getGrandParentCategories(storeTypeID: storeTypeID) { (categories: [GrandParentCategoryModel], error: String?) in
            self.categories = categories
            
            let response = GrandParentCategories.GetCategories.Response(categories: categories, error: error)
            self.presenter?.presentCategories(response: response)
        }
    }
}
