//
//  HelpAndFeedbackInteractor.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 07/06/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HelpAndFeedbackBusinessLogic
{
    func getSettings(request: HelpAndFeedback.GetSettings.Request)
    
    func setFeedbackTitle(setting: SettingModel)
}

protocol HelpAndFeedbackDataStore
{
    var selectedSetting: SettingModel! { get set }
}

class HelpAndFeedbackInteractor: HelpAndFeedbackBusinessLogic, HelpAndFeedbackDataStore
{
    var presenter: HelpAndFeedbackPresentationLogic?
    var worker: HelpAndFeedbackWorker?
    
    var selectedSetting: SettingModel!
    
    func getSettings(request: HelpAndFeedback.GetSettings.Request)
    {
        let response = HelpAndFeedback.GetSettings.Response()
        presenter?.presentSettings(response: response)
    }
    
    func setFeedbackTitle(setting: SettingModel){
        self.selectedSetting = setting
    }
}
