//
//  ShowRefineModels.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 02/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ShowRefine
{
    // MARK: Use cases
    
    enum GetSearchRefine
    {
        struct Request
        {
        }
        struct Response
        {
            var searchRefine: SearchRefine
        }
        struct ViewModel
        {
            var brands: [RefineBrandOptionModel]
            var categories: [RefineCategoryOptionModel]
            var promotions: [RefinePromotionOptionModel]
        }
    }
    
    
    enum GetSelectedOptions
    {
        struct Request
        {
        }
        struct Response
        {
            var selectedRefineOptions: SelectedRefineOptions
        }
        struct ViewModel
        {
            var selectedRefineOptions: SelectedRefineOptions
        }
    }
    
    enum UpdatedSelectedOptions
    {
        struct Request
        {
            var option: RefineOptionModel
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
}
