//
//  ShowRefineInteractor.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 02/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowRefineBusinessLogic
{
  func doSomething(request: ShowRefine.Something.Request)
}

protocol ShowRefineDataStore
{
  //var name: String { get set }
}

class ShowRefineInteractor: ShowRefineBusinessLogic, ShowRefineDataStore
{
  var presenter: ShowRefinePresentationLogic?
  var worker: ShowRefineWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ShowRefine.Something.Request)
  {
    worker = ShowRefineWorker()
    worker?.doSomeWork()
    
    let response = ShowRefine.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
