//
//  ShowRefinePresenter.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 02/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowRefinePresentationLogic
{
  func presentSomething(response: ShowRefine.Something.Response)
}

class ShowRefinePresenter: ShowRefinePresentationLogic
{
  weak var viewController: ShowRefineDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ShowRefine.Something.Response)
  {
    let viewModel = ShowRefine.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
