//
//  SendEmailPresenter.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 26/02/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SendEmailPresentationLogic
{
  func presentSomething(response: SendEmail.Something.Response)
}

class SendEmailPresenter: SendEmailPresentationLogic
{
  weak var viewController: SendEmailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SendEmail.Something.Response)
  {
    let viewModel = SendEmail.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
