//
//  VerifyCodeInteractor.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 26/02/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VerifyCodeBusinessLogic
{
  func doSomething(request: VerifyCode.Something.Request)
}

protocol VerifyCodeDataStore
{
  //var name: String { get set }
}

class VerifyCodeInteractor: VerifyCodeBusinessLogic, VerifyCodeDataStore
{
  var presenter: VerifyCodePresentationLogic?
  var worker: VerifyCodeWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: VerifyCode.Something.Request)
  {
    worker = VerifyCodeWorker()
    worker?.doSomeWork()
    
    let response = VerifyCode.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
