////
////  StorePresenterTests.swift
////  SuperStore
////
////  Created by Zakariya Mohummed on 23/03/2021.
////  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
////
////  This file was generated by the Clean Swift Xcode Templates so
////  you can apply clean architecture to your iOS and Mac projects,
////  see http://clean-swift.com
////
//
//@testable import SuperStore
//import XCTest
//
//class StorePresenterTests: XCTestCase
//{
//  // MARK: Subject under test
//  
//  var sut: StorePresenter!
//  
//  // MARK: Test lifecycle
//  
//  override func setUp()
//  {
//    super.setUp()
//    setupStorePresenter()
//  }
//  
//  override func tearDown()
//  {
//    super.tearDown()
//  }
//  
//  // MARK: Test setup
//  
//  func setupStorePresenter()
//  {
//    sut = StorePresenter()
//  }
//  
//  // MARK: Test doubles
//  
//  class StoreDisplayLogicSpy: StoreDisplayLogic
//  {
//    var displaySomethingCalled = false
//    
//    func displaySomething(viewModel: Store.Something.ViewModel)
//    {
//      displaySomethingCalled = true
//    }
//  }
//  
//  // MARK: Tests
//  
//  func testPresentSomething()
//  {
//    // Given
//    let spy = StoreDisplayLogicSpy()
//    sut.viewController = spy
//    let response = Store.Something.Response()
//    
//    // When
//    sut.presentSomething(response: response)
//    
//    // Then
//    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
//  }
//}
