//
//  FavouritesRouter.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 01/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FavouritesRoutingLogic
{
    func routeToShowProduct(segue: UIStoryboardSegue?)
    func routeToLogin(segue: UIStoryboardSegue?)
}

protocol FavouritesDataPassing
{
    var dataStore: FavouritesDataStore? { get }
    var selectedProductID: Int? { get set }
}

class FavouritesRouter: NSObject, FavouritesRoutingLogic, FavouritesDataPassing
{
    weak var viewController: FavouritesViewController?
    
    var dataStore: FavouritesDataStore?
    var selectedProductID: Int?
    
    // MARK: Routing
    
    func routeToShowProduct(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! ShowProductViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowProduct(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "ShowProductViewController") as! ShowProductViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowProduct(source: dataStore!, destination: &destinationDS)
            navigateToShowProduct(source: viewController!, destination: destinationVC)
        }
    }
    
    func routeToLogin(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! LoginViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToLogin(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "LoginViewController") as! LoginViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToLogin(source: dataStore!, destination: &destinationDS)
            navigateToLogin(source: viewController!, destination: destinationVC)
        }
    }
    
    //    MARK: Navigation
    
    func navigateToShowProduct(source: FavouritesViewController, destination: ShowProductViewController)
    {
        source.show(destination, sender: nil)
    }
    
    func navigateToLogin(source: FavouritesViewController, destination: LoginViewController)
    {
        source.present(destination, animated: true, completion: nil)
    }
    
    //    MARK: Passing data
    
    func passDataToShowProduct(source: FavouritesDataStore, destination: inout ShowProductDataStore)
    {
        destination.productID = selectedProductID!
    }
    
    func passDataToLogin(source: FavouritesDataStore, destination: inout LoginDataStore)
    {
        
    }
}
