//
//  MonitoredProductsViewController.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 03/05/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MonitoredProductsDisplayLogic: AnyObject
{
    func displayMonitoredProducts(viewModel: MonitoredProducts.GetMonitoredProducts.ViewModel)
    func displayDeletedMonitoredProduct(viewModel: MonitoredProducts.DeleteMonitoredProduct.ViewModel)
}

class MonitoredProductsViewController: UIViewController, MonitoredProductsDisplayLogic, UITableViewDelegate, UITableViewDataSource
{
    var interactor: MonitoredProductsBusinessLogic?
    var router: (NSObjectProtocol & MonitoredProductsRoutingLogic & MonitoredProductsDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = MonitoredProductsInteractor()
        let presenter = MonitoredProductsPresenter()
        let router = MonitoredProductsRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        getMonitoringProducts()
    }
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        setupTableView()
        getMonitoringProducts()
    }
    
    @IBOutlet var monitorTableView: UITableView!
    
    var loading: Bool = false
    
    var refreshControl = UIRefreshControl()
    
    var products: [ProductModel] = []
    
    func getMonitoringProducts()
    {
        let request = MonitoredProducts.GetMonitoredProducts.Request()
        interactor?.getMonitoredProducts(request: request)
    }
    
    func displayMonitoredProducts(viewModel: MonitoredProducts.GetMonitoredProducts.ViewModel)
    {
        refreshControl.endRefreshing()
        
        if let error = viewModel.error {
            if !viewModel.offline {
                showError(title: "Monitored Products Error", error: error)
            }
        } else {
            loading = false
            products = viewModel.products
            monitorTableView.reloadData()
        }
    }
    
    func displayDeletedMonitoredProduct(viewModel: MonitoredProducts.DeleteMonitoredProduct.ViewModel) {
        if let error = viewModel.error {
            showError(title: "Monitored Products Error", error: error)
        }
    }
}

extension MonitoredProductsViewController {
    func setupTableView(){
        let productCellNib = UINib(nibName: "ProductCell", bundle: nil)
        monitorTableView.register(productCellNib, forCellReuseIdentifier: "ProductCell")
        
        monitorTableView.delegate = self
        monitorTableView.dataSource = self
        
        setupRefreshControl()
    }
    

    func setupRefreshControl(){
        refreshControl.attributedTitle = NSAttributedString(string: "Pull To Refresh")
        refreshControl.addTarget(self, action: #selector(refreshMonitor), for: .valueChanged)
        monitorTableView.addSubview(refreshControl)
    }
    
    @objc func refreshMonitor(){
        getMonitoringProducts()
    }
}

extension MonitoredProductsViewController {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return products.count
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let product = products[indexPath.row]
        interactor?.setSelectedProduct(productID: product.id)
        router?.routeToShowProduct(segue: nil)
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        return configureProductCell(indexPath: indexPath)
    }
    
    func deleteMonitored(indexPath: IndexPath){
        let deleteProduct = products[indexPath.row]
        
        let request = MonitoredProducts.DeleteMonitoredProduct.Request(productID: deleteProduct.id)
        interactor?.deleteMonitoredProduct(request: request)
        
        products.remove(at: indexPath.row)
        monitorTableView.deleteRows(at: [indexPath], with: .fade)
    }
    
    func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCell.EditingStyle, forRowAt indexPath: IndexPath) {
        if editingStyle == .delete {
            deleteMonitored(indexPath: indexPath)
        }
    }
    
    func configureProductCell(indexPath: IndexPath) -> ProductCell {
        let cell = monitorTableView.dequeueReusableCell(withIdentifier: "ProductCell", for: indexPath) as! ProductCell
        
        cell.loading = loading
        cell.product = loading ? nil : products[indexPath.row]
        cell.configureUI()
        
        cell.selectionStyle = UITableViewCell.SelectionStyle.none
        
        return cell
    }
}
