//
//  EditRegionInteractor.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 26/05/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditRegionBusinessLogic
{
  func doSomething(request: EditRegion.Something.Request)
}

protocol EditRegionDataStore
{
  //var name: String { get set }
}

class EditRegionInteractor: EditRegionBusinessLogic, EditRegionDataStore
{
  var presenter: EditRegionPresentationLogic?
  var worker: EditRegionWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: EditRegion.Something.Request)
  {
    worker = EditRegionWorker()
    worker?.doSomeWork()
    
    let response = EditRegion.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
