//
//  EditRegionInteractor.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 26/05/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditRegionBusinessLogic
{
    func getRegions(request: EditRegion.GetRegions.Request)
    func updateRegion(request: EditRegion.UpdateRegion.Request)
}

protocol EditRegionDataStore
{
}

class EditRegionInteractor: EditRegionBusinessLogic, EditRegionDataStore
{
    var presenter: EditRegionPresentationLogic?

    var regionWorker: RegionWorker = RegionWorker()
    
    var userSessionWorker: UserSessionWorker = UserSessionWorker()
    var userSettingsWorker: UserSettingsWorker = UserSettingsWorker(userStore: UserRealmStore())
    
    func getRegions(request: EditRegion.GetRegions.Request)
    {
        let regions = regionWorker.getRegionsForSupermarketChain()
        let selectedRegionID = regionWorker.getSelectedRegion().id
        
        let response = EditRegion.GetRegions.Response(regions: regions, selectedRegionID: selectedRegionID)
        presenter?.presentRegions(response: response)
    }
    
    func updateRegion(request: EditRegion.UpdateRegion.Request){
        let region = request.region
        
        let loggedIn: Bool = userSessionWorker.isLoggedIn()
        
        userSettingsWorker.updateRegion(regionID: region.id, loggedIn: loggedIn) { (error: String?) in
            let response = EditRegion.UpdateRegion.Response(error: error)
            self.presenter?.presentUpdatedRegion(response: response)
        }
    }
}
