//
//  ShowIngredientsPresenter.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 28/02/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowItemsPresentationLogic
{
    func presentSomething(response: ShowItems.GetItems.Response)
}

class ShowItemsPresenter: ShowItemsPresentationLogic
{
    weak var viewController: ShowItemsDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: ShowItems.GetItems.Response)
    {
        let viewModel = ShowItems.GetItems.ViewModel(title: response.title, items: response.items)
        viewController?.displayItems(viewModel: viewModel)
    }
}
