//
//  ShowIngredientsInteractor.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 28/02/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowIngredientsBusinessLogic
{
    func getItems(request: ShowItems.GetItems.Request)
}

protocol ShowItemsDataStore
{
    var title: String { get set }
    var items: [String] { get set }
}

class ShowItemsInteractor: ShowIngredientsBusinessLogic, ShowItemsDataStore
{
    var presenter: ShowItemsPresentationLogic?
    var worker: ShowItemsWorker?
    
    var title: String = ""
    var items: [String] = []
    
    func getItems(request: ShowItems.GetItems.Request)
    {
        let response = ShowItems.GetItems.Response(title: title, items: items)
        presenter?.presentSomething(response: response)
    }
}
