//
//  EditListItemInteractor.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 05/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditListItemBusinessLogic
{
    func getListItem(request: EditListItem.GetListItem.Request)
    func updateQuantity(request: EditListItem.UpdateQuantity.Request)
    func deleteListItem(request: EditListItem.DeleteListItem.Request)
    func updateListItem(request: EditListItem.UpdateListItem.Request)
}

protocol EditListItemDataStore
{
    var listID: Int! { get set }
    var listItem: ListItemModel! { get set }
}

class EditListItemInteractor: EditListItemBusinessLogic, EditListItemDataStore
{
    
    var presenter: EditListItemPresentationLogic?
    
    var listPriceWorker: ListPriceWorker = ListPriceWorker()
    var listItemWorker: ListItemWorker = ListItemWorker(listItemAPI: ListItemAPI())
    
    var userSession = UserSessionWorker()
    
    var listID: Int!
    var listItem: ListItemModel!
    
    func getListItem(request: EditListItem.GetListItem.Request)
    {
        let response = EditListItem.GetListItem.Response(listItem: listItem)
        presenter?.presentListItem(response: response)
    }
    
    func updateQuantity(request: EditListItem.UpdateQuantity.Request){
        let quantity = request.quantity

        listItem.quantity = quantity
        listItem.totalPrice = listPriceWorker.calculateItemPrice(listItem: listItem)
        
        let response = EditListItem.UpdateQuantity.Response(listItem: listItem)
        presenter?.presentListItemQuantityUpdated(response: response)
    }

    func deleteListItem(request: EditListItem.DeleteListItem.Request){
        let productID: Int = listItem.productID
        
        listItemWorker.deleteItem(listID: listID, productID: productID) { (error: String?) in
            var response = EditListItem.DeleteListItem.Response(error: error)
            
            if error != nil {
                response.offline = !self.userSession.isOnline()
            }
            
            self.presenter?.presentListItemDeleted(response: response)
        }
    }
    
    func updateListItem(request: EditListItem.UpdateListItem.Request) {
        let productID: Int = listItem.productID
        let quantity: Int = listItem.quantity
        let tickedOff = listItem.tickedOff
        
        listItemWorker.updateItem(listID: listID, productID: productID, quantity: quantity, tickedOff: tickedOff, totalPrice: listItem.totalPrice) { (error: String?) in
            var response = EditListItem.UpdateListItem.Response(error: error)
            
            if error != nil {
                response.offline = !self.userSession.isOnline()
            }
            
            self.presenter?.presentListItemUpdated(response: response)
        }
    }
}
