//
//  AdvancedSettingsModels.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 07/06/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AdvancedSettings
{
    // MARK: Use cases
    
    struct DisplaySection {
        var title: String = ""
        var settings: [SettingModel]
    }
    
    struct DisplayCell {
        var name: String
    }
    
    enum GetSettings
    {
        struct Request
        {
        }
        
        struct Response
        {
            var parentSetting: SettingModel
            
            var user: UserModel?
            
            var supermarketChainName: String
            var regionName: String
            
            var unreadHelpMessages: Int
            var unreadFeaturepMessages: Int
            var unreadIssueMessages: Int
            var unreadFeedbackMessages: Int
            
            var loggedIn: Bool
        }
        
        struct ViewModel
        {
            var parentSetting: SettingModel
            var displaySections: [DisplaySection]
        }
    }
    
    
    enum Delete
    {
        struct Request
        {
        }
        
        struct Response
        {
            var error: String?
        }
        
        struct ViewModel
        {
            var error: String?
        }
    }
}
