//
//  ShowListsRouter.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 04/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ShowListsRoutingLogic
{
    func routeToEditList(segue: UIStoryboardSegue?)
    func routeToShowList(segue: UIStoryboardSegue?)
}

protocol ShowListsDataPassing
{
    var dataStore: ShowListsDataStore? { get }
}

class ShowListsRouter: NSObject, ShowListsRoutingLogic, ShowListsDataPassing
{
    weak var viewController: ShowListsViewController?
    var dataStore: ShowListsDataStore?
    
    // MARK: Routing
    
    func routeToEditList(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! EditListViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToEditList(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "EditListViewController") as! EditListViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToEditList(source: dataStore!, destination: &destinationDS)
            navigateToEditList(source: viewController!, destination: destinationVC)
        }
    }
    
    func routeToShowList(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! ShowListViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowList(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "ShowListViewController") as! ShowListViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowList(source: dataStore!, destination: &destinationDS)
            navigateToShowList(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToEditList(source: ShowListsViewController, destination: EditListViewController)
    {
        source.show(destination, sender: nil)
    }
    
    func navigateToShowList(source: ShowListsViewController, destination: ShowListViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToEditList(source: ShowListsDataStore, destination: inout EditListDataStore)
    {
        let list =  source.lists[ viewController!.editIndexPath!.row ]
        destination.list = list
    }
    
    func passDataToShowList(source: ShowListsDataStore, destination: inout ShowListDataStore)
    {
        let list =  source.lists[ viewController!.listsTableView.indexPathForSelectedRow!.row ]
        destination.list = list
    }
    
}
