//
//  GroceryTableInteractor.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 03/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GroceryTableBusinessLogic
{
  func doSomething(request: GroceryTable.Something.Request)
}

protocol GroceryTableDataStore
{
  //var name: String { get set }
}

class GroceryTableInteractor: GroceryTableBusinessLogic, GroceryTableDataStore
{
  var presenter: GroceryTablePresentationLogic?
  var worker: GroceryTableWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: GroceryTable.Something.Request)
  {
    worker = GroceryTableWorker()
    worker?.doSomeWork()
    
    let response = GroceryTable.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
