//
//  RegisterViewController.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 26/02/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegisterDisplayLogic: class
{
  func displayUserEmail(viewModel: Register.GetEmail.ViewModel)
}

class RegisterViewController: UIViewController, RegisterDisplayLogic
{
  var interactor: RegisterBusinessLogic?
  var router: (NSObjectProtocol & RegisterRoutingLogic & RegisterDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = RegisterInteractor()
    let presenter = RegisterPresenter()
    let router = RegisterRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    displayEmailFromLoginForm()
  }
  
  // MARK: Do something
  
    @IBOutlet weak var nameField: UITextField!
    @IBOutlet weak var emailField: UITextField!
    @IBOutlet weak var passwordField: UITextField!
    @IBOutlet weak var passwordConfirmField: UITextField!
    
  //@IBOutlet weak var nameTextField: UITextField!
  
    @IBAction func registerButtonPressed(_ sender: Any) {
        var name = nameField.text ?? ""
        var email = emailField.text ?? ""
        var password = passwordField.text ?? ""
        var passwordConfirm = passwordConfirmField.text ?? ""
        
        var request = Register.Register.Request(name: name, email: email, password: password, passwordConfirm: passwordConfirm)
        interactor?.register(request: request)
    }
    
    func displayEmailFromLoginForm()
  {
    let request = Register.GetEmail.Request()
    interactor?.getEmail(request: request)
  }
  
  func displayUserEmail(viewModel: Register.GetEmail.ViewModel)
  {
    print(viewModel)
    emailField.text = viewModel.email
  }
}
