//
//  RegisterInteractor.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 26/02/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegisterBusinessLogic
{
    func register(request: Register.Register.Request)
    func getEmail(request: Register.GetEmail.Request)
}

protocol RegisterDataStore
{
    var email: String? { get set }
}

class RegisterInteractor: RegisterBusinessLogic, RegisterDataStore
{
    var presenter: RegisterPresentationLogic?
    var worker: UserValidationWorker = UserValidationWorker()
    
    var email: String?
    
    // MARK: Do something
    func register(request: Register.Register.Request){
        
    }
    
    func getEmail(request: Register.GetEmail.Request)
    {
        let response = Register.GetEmail.Response(email: email)
        presenter?.presentUserEmail(response: response)
    }
}
