//
//  FlyerListRouter.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 23/05/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FlyerListRoutingLogic
{
    func routeToShowFlyer(segue: UIStoryboardSegue?)
}

protocol FlyerListDataPassing
{
    var dataStore: FlyerListDataStore? { get }
}

class FlyerListRouter: NSObject, FlyerListRoutingLogic, FlyerListDataPassing
{
    weak var viewController: FlyerListViewController?
    var dataStore: FlyerListDataStore?
    
    // MARK: Routing
    
    func routeToShowFlyer(segue: UIStoryboardSegue?)
    {
      if let segue = segue {
        let destinationVC = segue.destination as! ShowFlyerViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
      } else {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "ShowFlyerViewController") as! ShowFlyerViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        navigateToSomewhere(source: viewController!, destination: destinationVC)
      }
    }
    
    // MARK: Navigation
    
    func navigateToSomewhere(source: FlyerListViewController, destination: ShowFlyerViewController)
    {
      source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToSomewhere(source: FlyerListDataStore, destination: inout ShowFlyerDataStore)
    {
        destination.flyer = source.selectedFlyer
    }
}
