//
//  SettingsRouter.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 03/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SettingsRoutingLogic
{
    func routeToEditName(segue: UIStoryboardSegue?)
    func routeToEditEmail(segue: UIStoryboardSegue?)
    func routeToEditPassword(segue: UIStoryboardSegue?)
    func routeToLogin(segue: UIStoryboardSegue?)
    func routeToHome(segue: UIStoryboardSegue?)
}

protocol SettingsDataPassing
{
    var dataStore: SettingsDataStore? { get }
}

class SettingsRouter: NSObject, SettingsRoutingLogic, SettingsDataPassing
{
    weak var viewController: SettingsViewController?
    var dataStore: SettingsDataStore?
    
    // MARK: Routing

    func routeToLogin(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! LoginViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToLogin(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "LoginViewController") as! LoginViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToLogin(source: dataStore!, destination: &destinationDS)
            navigateToLogin(source: viewController!, destination: destinationVC)
        }
    }
    
    func routeToHome(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! HomeViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToHome(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "HomeViewController") as! HomeViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToHome(source: dataStore!, destination: &destinationDS)
            navigateToHome(source: viewController!, destination: destinationVC)
        }
    }
    
    func routeToEditName(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! EditNameViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToEditName(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "EditNameViewController") as! EditNameViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToEditName(source: dataStore!, destination: &destinationDS)
            navigateToEditName(source: viewController!, destination: destinationVC)
        }
    }
    
    func routeToEditEmail(segue: UIStoryboardSegue?)
    {
      if let segue = segue {
        let destinationVC = segue.destination as! EditEmailViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToEditEmail(source: dataStore!, destination: &destinationDS)
      } else {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "EditEmailViewController") as! EditEmailViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToEditEmail(source: dataStore!, destination: &destinationDS)
        navigateToEditEmail(source: viewController!, destination: destinationVC)
      }
    }
    
    func routeToEditPassword(segue: UIStoryboardSegue?)
    {
      if let segue = segue {
        let destinationVC = segue.destination as! EditPasswordViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToEditPassword(source: dataStore!, destination: &destinationDS)
      } else {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "EditPasswordViewController") as! EditPasswordViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToEditPassword(source: dataStore!, destination: &destinationDS)
        navigateToEditPassword(source: viewController!, destination: destinationVC)
      }
    }
    
    // MARK: Navigation
    
    func navigateToLogin(source: SettingsViewController, destination: LoginViewController)
    {
        source.present(destination, animated: true, completion: nil)
    }
    
    func navigateToHome(source: SettingsViewController, destination: HomeViewController)
    {
        source.navigationController?.popToRootViewController(animated: true)
    }
    
    func navigateToEditName(source: SettingsViewController, destination: EditNameViewController)
    {
        source.show(destination, sender: nil)
    }
    
    func navigateToEditEmail(source: SettingsViewController, destination: EditEmailViewController)
    {
        source.show(destination, sender: nil)
    }
    
    func navigateToEditPassword(source: SettingsViewController, destination: EditPasswordViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToLogin(source: SettingsDataStore, destination: inout LoginDataStore)
    {

    }
    
    func passDataToHome(source: SettingsDataStore, destination: inout HomeDataStore)
    {

    }
    
    func passDataToEditName(source: SettingsDataStore, destination: inout EditNameDataStore)
    {
        destination.name = source.user!.name
    }
    
    func passDataToEditEmail(source: SettingsDataStore, destination: inout EditEmailDataStore)
    {
        destination.email = source.user!.email
    }
    
    func passDataToEditPassword(source: SettingsDataStore, destination: inout EditPasswordDataStore)
    {

    }

}
