//
//  SettingsRouter.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 03/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SettingsRoutingLogic
{
    func routeToLogin(segue: UIStoryboardSegue?)
    func routeToAdvancedSettings(segue: UIStoryboardSegue?)
    func routeToEditRegion(segue: UIStoryboardSegue?)
}

protocol SettingsDataPassing
{
    var dataStore: SettingsDataStore? { get }
}

class SettingsRouter: NSObject, SettingsRoutingLogic, SettingsDataPassing
{
    
    weak var viewController: SettingsViewController?
    var dataStore: SettingsDataStore?
    
    // MARK: Routing
    
    func routeToLogin(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! LoginViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToLogin(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "LoginViewController") as! LoginViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToLogin(source: dataStore!, destination: &destinationDS)
            navigateToLogin(source: viewController!, destination: destinationVC)
        }
    }
    
    func routeToAdvancedSettings(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! AdvancedSettingsViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToAdvancedSettings(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "AdvancedSettingsViewController") as! AdvancedSettingsViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToAdvancedSettings(source: dataStore!, destination: &destinationDS)
            navigateToAdvancedSettings(source: viewController!, destination: destinationVC)
        }
    }

    func routeToEditRegion(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! EditRegionViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToEditRegion(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "EditRegionViewController") as! EditRegionViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToEditRegion(source: dataStore!, destination: &destinationDS)
            navigateToEditRegion(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToAdvancedSettings(source: SettingsViewController, destination: AdvancedSettingsViewController)
    {
        source.show(destination, sender: nil)
    }

    func navigateToLogin(source: SettingsViewController, destination: LoginViewController)
    {
        source.present(destination, animated: true, completion: nil)
    }
    
    func navigateToEditRegion(source: SettingsViewController, destination: EditRegionViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToAdvancedSettings(source: SettingsDataStore, destination: inout AdvancedSettingsDataStore)
    {
        destination.parentSetting = source.selectedSetting!
    }
    
    func passDataToLogin(source: SettingsDataStore, destination: inout LoginDataStore)
    {
        
    }
    
    func passDataToEditRegion(source: SettingsDataStore, destination: inout EditRegionDataStore)
    {
        
    }
}
