//
//  FavouritesWorkerTests.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 24/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import SuperStore
import XCTest

class FavouritesWorkerTests: XCTestCase
{
//  // MARK: Subject under test
//  
//  var sut: FavouritesWorker!
//  
//  // MARK: Test lifecycle
//  
//  override func setUp()
//  {
//    super.setUp()
//    setupFavouritesWorker()
//  }
//  
//  override func tearDown()
//  {
//    super.tearDown()
//  }
//  
//  // MARK: Test setup
//  
//  func setupFavouritesWorker()
//  {
//    sut = FavouritesWorker()
//  }
//  
//  // MARK: Test doubles
//  
//  // MARK: Tests
//  
//  func testSomething()
//  {
//    // Given
//    
//    // When
//    
//    // Then
//  }
}
