//
//  ShowDetailsInteractor.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 28/02/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowDetailsBusinessLogic
{
  func doSomething(request: ShowDetails.Something.Request)
}

protocol ShowDetailsDataStore
{
  //var name: String { get set }
}

class ShowDetailsInteractor: ShowDetailsBusinessLogic, ShowDetailsDataStore
{
  var presenter: ShowDetailsPresentationLogic?
  var worker: ShowDetailsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ShowDetails.Something.Request)
  {
    worker = ShowDetailsWorker()
    worker?.doSomeWork()
    
    let response = ShowDetails.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
