//
//  StoreModels.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 02/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Store
{
    
    struct DisplayedStore {
        var name: String
        var logo: String
        var logoImage: UIImage?
        var address: String
        var storeTypeID: Int
        
        var openingHours: [DisplayOpeningHour]
//        var facilities: [String]
        var facilities: [DisplayFacility]
    }
    
    struct DisplayOpeningHour {
        var today: Bool
        var hours: String
        var day: String
        var dayOfWeek: Int
        var closedToday: Bool
    }

    struct DisplayFacility {
        var name: String
        var icon: UIImage
    }
    
    enum GetStore
    {
        struct Request
        {
        }
        
        struct Response
        {
            var store: StoreModel?
            var error: String?
        }
        
        struct ViewModel
        {
            var displayedStore: DisplayedStore?
            var error: String?
        }
    }
}
