//
//  ShowStoreResultsInteractor.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 02/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowStoreResultsBusinessLogic
{
  func doSomething(request: ShowStoreResults.Something.Request)
}

protocol ShowStoreResultsDataStore
{
  //var name: String { get set }
}

class ShowStoreResultsInteractor: ShowStoreResultsBusinessLogic, ShowStoreResultsDataStore
{
  var presenter: ShowStoreResultsPresentationLogic?
  var worker: ShowStoreResultsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ShowStoreResults.Something.Request)
  {
    worker = ShowStoreResultsWorker()
    worker?.doSomeWork()
    
    let response = ShowStoreResults.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
