//
//  ShowStoreResultsPresenter.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 02/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowStoreResultsPresentationLogic
{
  func presentStores(response: ShowStoreResults.GetStores.Response)
}

class ShowStoreResultsPresenter: ShowStoreResultsPresentationLogic
{
  weak var viewController: ShowStoreResultsDisplayLogic?
  
  // MARK: Do something
  
  func presentStores(response: ShowStoreResults.GetStores.Response)
  {
    let viewModel = ShowStoreResults.GetStores.ViewModel(stores: response.stores, error: response.error)
    viewController?.displayStores(viewModel: viewModel)
  }
}
