//
//  ChildCategoriesRouter.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 03/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ChildCategoriesRoutingLogic
{
    func routeToShowProduct(segue: UIStoryboardSegue?)
    func routeToShowList(segue: UIStoryboardSegue?)
}

protocol ChildCategoriesDataPassing
{
    var dataStore: ChildCategoriesDataStore? { get }
    var selectedProductID: Int? { get set }
}

class ChildCategoriesRouter: BackToShowListRouter, ChildCategoriesRoutingLogic, ChildCategoriesDataPassing
{
    var childCategoriesViewController: ChildCategoriesViewController {
        return viewController as! ChildCategoriesViewController
    }
    
    var dataStore: ChildCategoriesDataStore?
    var selectedProductID: Int?
    
    // MARK: Routing
    
    func routeToShowProduct(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! ShowProductViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowProduct(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "ShowProductViewController") as! ShowProductViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowProduct(source: dataStore!, destination: &destinationDS)
            navigateToShowProduct(source: childCategoriesViewController, destination: destinationVC)
        }
    }
    
    //    MARK: Navigation
    
    func navigateToShowProduct(source: ChildCategoriesViewController, destination: ShowProductViewController)
    {
        source.show(destination, sender: nil)
    }
    
    //    MARK: Passing data
    
    func passDataToShowProduct(source: ChildCategoriesDataStore, destination: inout ShowProductDataStore)
    {
        destination.productID = selectedProductID!
        destination.selectedListID = source.selectedListID
    }
}
