//
//  ChildCategoriesViewController.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 03/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Tabman
import Pageboy

protocol ChildCategoriesDisplayLogic: class
{
    func displayCategories(viewModel: ChildCategories.GetCategories.ViewModel)
    func displayListItems(viewModel: ChildCategories.GetListItems.ViewModel)
    func displayListItemCreated(viewModel: ChildCategories.CreateListItem.ViewModel)
    func displayListItemUpdated(viewModel: ChildCategories.UpdateListItem.ViewModel)
}

class ChildCategoriesViewController: TabmanViewController, ChildCategoriesDisplayLogic
{

    var interactor: ChildCategoriesBusinessLogic?
    var router: (NSObjectProtocol & ChildCategoriesRoutingLogic & ChildCategoriesDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = ChildCategoriesInteractor()
        let presenter = ChildCategoriesPresenter()
        let router = ChildCategoriesRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        displayRightBarButton()
        setupBar()
        
        getListItems()
        getCategories()
    }
    
    var loading: Bool = true
    
    var selectedProduct: ProductModel?
    var selectedSection: Int?
    
    var viewcontrollers:[GroceryTableViewController] = [ GroceryTableViewController(nibName: nil, bundle: nil) ]
    var categories: [ChildCategoryModel] = []
    
    var listItems: [Int: ListItemModel] = [:]
    
    let bar = TMBar.ButtonBar()
    
    func getCategories()
    {
        let request = ChildCategories.GetCategories.Request()
        interactor?.getCategories(request: request)
    }
    
    func getListItems(){
        let request = ChildCategories.GetListItems.Request()
        interactor?.getListItems(request: request)
    }
    
    func displayCategories(viewModel: ChildCategories.GetCategories.ViewModel)
    {

        if let error = viewModel.error {
            if !viewModel.offline {
                showError(title: "Grocery Error", error: error)
            }
        } else {
            loading = false
            
            reloadTableView()
            
            self.categories = viewModel.categories
            viewcontrollers = categories.map { _ in GroceryTableViewController(nibName: nil, bundle: nil) }
            self.reloadData()
        }
    }
    
    func displayListItems(viewModel: ChildCategories.GetListItems.ViewModel) {
        self.listItems = viewModel.listItems
    }
    
    func displayListItemCreated(viewModel: ChildCategories.CreateListItem.ViewModel) {
        if let error = viewModel.error {
            if !viewModel.offline {
                showError(title: "List Error", error: error)
            }
        } else {
            // If list item exists locally,
            if let listItem = viewModel.listItem {
                updateProductQuantity(section: viewModel.section, productID: listItem.productID, quantity: listItem.quantity)
                reloadTableView()
            }
        }
    }
    
    func displayListItemUpdated(viewModel: ChildCategories.UpdateListItem.ViewModel) {
        if let error = viewModel.error, viewModel.offline {
            showError(title: "List Error", error: error)
        }
    }

}

extension ChildCategoriesViewController {
    func displayRightBarButton(){
        if interactor?.selectedListID == nil {
            self.navigationItem.rightBarButtonItem = nil
        }
    }
}

extension ChildCategoriesViewController {
    func setupBar(){
        self.dataSource = self
        configureBar()
    }
    
    func configureBar(){
        bar.tintColor = UIColor(named: "Label Color")
        
        bar.layout.contentInset = UIEdgeInsets(top: 0.0, left: 16.0, bottom: 1.0, right: 16.0)
        bar.layout.interButtonSpacing = 30.0
        
        bar.layout.showSeparators = true
        bar.layout.separatorColor = UIColor(red: 0.83, green: 0.83, blue: 0.83, alpha: 1.00)
        bar.layout.separatorWidth = 0.5
        
        bar.backgroundView.style = .flat(color:  UIColor(named: "LightGrey")!)
        bar.backgroundColor = UIColor(named: "LightGrey")
        
        bar.indicator.weight = .medium
        bar.indicator.cornerStyle = .square
        bar.fadesContentEdges = true
        bar.spacing = 30.0
        
        // Add to view
        addBar(bar, dataSource: self, at: .top)
    }
}

extension ChildCategoriesViewController:  TMBarDataSource, PageboyViewControllerDataSource {
    func barItem(for bar: TMBar, at index: Int) -> TMBarItemable {
        let title: String = loading ? "" : categories[index].name
        return TMBarItem(title: title)
    }
    
    func numberOfViewControllers(in pageboyViewController: PageboyViewController) -> Int {
        return viewcontrollers.count
    }
    
    func viewController(for pageboyViewController: PageboyViewController, at index: PageboyViewController.PageIndex) -> UIViewController? {
        let viewController: GroceryTableViewController = viewcontrollers[index]
        
        viewController.loading = loading
        
        if !loading && categories.indices.contains(index) {
            viewController.section = index
            viewController.selectedListID = interactor?.selectedListID
            viewController.listItems = listItems
            
            viewController.products = categories[index].products
            
            viewController.productPressed = productPressed
            viewController.addToListPressedCallBack = addToListPressed
            viewController.updateQuantityPressedCallback = updateQuantityPressed
        }
        
        return viewController
    }
    
    func defaultPage(for pageboyViewController: PageboyViewController) -> PageboyViewController.Page? {
        return nil
    }
}

extension ChildCategoriesViewController {
    private func productPressed(productID: Int){
        router?.selectedProductID = productID
        router?.routeToShowProduct(segue: nil)
    }
}

extension ChildCategoriesViewController: SelectListProtocol {
    func addToListPressed(section: Int, product: ProductModel){
        // Show lists, select one.
        selectedProduct = product
        selectedSection = section

        if let listID = interactor?.selectedListID {
            updateProductQuantity(section: selectedSection!, productID: product.id, quantity: 1, listID: listID)
            createListItem(listID: listID)
            reloadTableView()
        } else {
            interactor?.selectedProductStoreTypeID = product.storeTypeID
            router?.routeToShowLists(segue: nil)
        }
        
    }
    
    func listSelected(listID: Int) {
        // Update Cell Quantity Button
        updateProductQuantity(section: selectedSection!, productID: selectedProduct!.id, quantity: 1, listID: listID)
        createListItem(listID: listID)
        reloadTableView()
    }
    
    func createListItem(listID: Int){
        let request = ChildCategories.CreateListItem.Request(
            listID: listID,
            product: selectedProduct!,
            section: selectedSection!
        )

        interactor?.createListItem(request: request)
    }
    
    func updateQuantityPressed(section: Int, product: ProductModel){
        // Update API/Realm Request
        selectedProduct = product
        let listID: Int =  product.listID!
        
        updateProductQuantity(section: section, productID: product.id, quantity: product.quantity)

        let request = ChildCategories.UpdateListItem.Request(
            listID: listID,
            productID: product.id,
            quantity: product.quantity
        )

        interactor?.updateListItem(request: request)
    }

    func updateProductQuantity(section: Int, productID: Int, quantity: Int, listID: Int? = nil){
        for searchProduct in categories[section].products {
            if searchProduct.id == productID {
                searchProduct.quantity = quantity

                if quantity == 0 {
                    searchProduct.listID = nil
                } else if listID != nil {
                    searchProduct.listID = listID!
                }
            }
        }
    }
    
    func reloadTableView(){
        for viewController in viewcontrollers {
            viewController.loading = loading
            viewController.tableView.reloadData()
        }
    }
}

extension ChildCategoriesViewController {
    @IBAction func doneButtonPressed(_ sender: UIBarButtonItem) {
        router?.routeToShowList(segue: nil)
    }
}
