//
//  ChildCategoriesInteractor.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 03/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChildCategoriesBusinessLogic
{
    func getCategories(request: ChildCategories.GetCategories.Request)
}

protocol ChildCategoriesDataStore
{
    var parentCategoryID: Int { get set }
}

class ChildCategoriesInteractor: ChildCategoriesBusinessLogic, ChildCategoriesDataStore
{
    var presenter: ChildCategoriesPresentationLogic?

    var parentCategoryID: Int = 1
    var groceryWorker: GroceryWorker = GroceryWorker(groceryAPI: GroceryAPI())
    
    // MARK: Do something
    
    func getCategories(request: ChildCategories.GetCategories.Request)
    {
        groceryWorker.getChildCategories(parentCategoryID: parentCategoryID) { (categories: [ChildCategoryModel], error: String?) in
            let response = ChildCategories.GetCategories.Response(categories: categories, error: error)
            self.presenter?.presentCategories(response: response)
        }
    }
}
