//
//  EditReviewModels.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 28/02/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum EditReview
{
    // MARK: Use cases
    
    struct ReviewFormFields {
        var text: String
        var title: String
        var rating: Double
    }
    
    enum GetReview
    {
        struct Request
        {
        }
        
        struct Response
        {
            var review: ReviewModel?
            var product: ProductModel?
            var error: String?
        }
        
        struct ViewModel
        {
            struct DisplayedReview {
                var id: Int
//                var image: String
//                var productName: String
                var text: String
                var title: String
                var rating: Double
                var name: String
            }
            
            var displayedReview: DisplayedReview?
            var error: String?
        }
    }
    
    enum GetProduct {
        struct Request
        {
        }
        
        struct Response
        {
            var product: ProductModel
        }
        
        struct ViewModel
        {
            struct DisplayedProduct {
                var name: String
                var image: String
            }
            
            var displayedProduct: DisplayedProduct?
        }
    }
    
    enum CreateReview {
        struct Request
        {
            var reviewFormField: ReviewFormFields
        }
        
        struct Response
        {
            var error: String?
        }
        
        struct ViewModel
        {
            var error: String?
        }
    }
    
    enum UpdateReview {
        struct Request
        {
            var reviewFormField: ReviewFormFields
        }
        
        struct Response
        {
            var error: String?
        }
        
        struct ViewModel
        {
            var error: String?
        }
    }
    
    enum DeleteReview {
        struct Request
        {
        }
        
        struct Response
        {
            var error: String?
        }
        
        struct ViewModel
        {
            var error: String?
        }
    }
}
