//
//  EditReviewRouter.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 28/02/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol EditReviewRoutingLogic
{
    func routeToProduct(segue: UIStoryboardSegue?)
}

protocol EditReviewDataPassing
{
    var dataStore: EditReviewDataStore? { get }
}

class EditReviewRouter: NSObject, EditReviewRoutingLogic, EditReviewDataPassing
{
    weak var viewController: EditReviewViewController?
    var dataStore: EditReviewDataStore?
    
    // MARK: Routing
    
    func routeToProduct(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! ShowProductViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowProduct(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "ShowProductViewController") as! ShowProductViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowProduct(source: dataStore!, destination: &destinationDS)
            navigateToShowProduct(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToShowProduct(source: EditReviewViewController, destination: ShowProductViewController)
    {
        source.navigationController?.popViewController(animated: true)
    }
    
    //   MARK: Passing data
    
    func passDataToShowProduct(source: EditReviewDataStore, destination: inout ShowProductDataStore)
    {
        
    }
}
