//
//  FeedbackModels.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 06/05/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Feedback
{
  // MARK: Use cases
  
  enum SendFeedback
  {
    struct Request
    {
        var message: String
    }
    struct Response
    {
        var error: String?
    }
    struct ViewModel
    {
        var error: String?
    }
  }
}
