//
//  FeedbackPresenter.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 06/05/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FeedbackPresentationLogic
{
    func presentTitle(response: Feedback.GetTitle.Response)
    func presentSendFeedback(response: Feedback.SendFeedback.Response)
}

class FeedbackPresenter: FeedbackPresentationLogic
{
    
    weak var viewController: FeedbackDisplayLogic?
    
    func presentTitle(response: Feedback.GetTitle.Response) {
        let viewModel = Feedback.GetTitle.ViewModel(title: response.title)
        viewController?.displayTitle(viewModel: viewModel)
    }
    
    func presentSendFeedback(response: Feedback.SendFeedback.Response)
    {
        let viewModel = Feedback.SendFeedback.ViewModel(error: response.error)
        viewController?.displaySendFeedback(viewModel: viewModel)
    }
}
