//
//  ShowSuggestionsInteractor.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 02/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowSuggestionsBusinessLogic
{
    func getSuggestions(request: ShowSuggestions.GetSuggestions.Request)
    var productQueryModel: ProductQueryModel? { get set }
}

protocol ShowSuggestionsDataStore
{
    var productQueryModel: ProductQueryModel? { get set }
}

class ShowSuggestionsInteractor: ShowSuggestionsBusinessLogic, ShowSuggestionsDataStore
{
    var presenter: ShowSuggestionsPresentationLogic?
    var searchWorker: SearchWorker = SearchWorker(searchAPI: SearchAPI())
    var productQueryModel: ProductQueryModel? = nil
    
    var userSession = UserSessionWorker()
    
    func getSuggestions(request: ShowSuggestions.GetSuggestions.Request)
    {
        let storeTypeID = userSession.getStore()
        
        searchWorker.getSuggestions(storeTypeID: storeTypeID, query: request.query) { (suggestions: [SuggestionModel], error: String?) in
            let response = ShowSuggestions.GetSuggestions.Response(suggestions: suggestions, error: error)
            self.presenter?.presentSuggestions(response: response)
        }
    }
}
