//
//  ShowSuggestionsModels.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 02/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ShowSuggestions
{
    // MARK: Use cases
    
    enum GetSuggestions
    {
        struct Request
        {
            var query: String
        }
        struct Response
        {
            var suggestions: [SuggestionModel]
            var error: String?
        }
        struct ViewModel
        {
            var suggestions: [SuggestionModel]
            var error: String?
        }
    }
    
    enum GetRecentSuggestions {
        struct Request
        {
            var limit: Int
        }
        struct Response
        {
            var suggestions: [SuggestionModel]
            var error: String?
        }
        struct ViewModel
        {
            var suggestions: [SuggestionModel]
            var error: String?
        }
    }
}
