//
//  ShowListInteractor.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 04/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowListBusinessLogic
{
  func doSomething(request: ShowList.Something.Request)
}

protocol ShowListDataStore
{
  //var name: String { get set }
}

class ShowListInteractor: ShowListBusinessLogic, ShowListDataStore
{
  var presenter: ShowListPresentationLogic?
  var worker: ShowListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ShowList.Something.Request)
  {
    worker = ShowListWorker()
    worker?.doSomeWork()
    
    let response = ShowList.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
