//
//  ShowListInteractor.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 04/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowListBusinessLogic
{
    func getList(request: ShowList.GetList.Request)
    var list: ListModel! { get set }
}

protocol ShowListDataStore
{
    var list: ListModel! { get set }
}

class ShowListInteractor: ShowListBusinessLogic, ShowListDataStore
{
    var presenter: ShowListPresentationLogic?
    var listWorker: ListWorker = ListWorker(listAPI: ListAPI())
    var list: ListModel!
    
    func getList(request: ShowList.GetList.Request)
    {
        listWorker.getList(listID: list.id) { (list: ListModel?, error: String?) in
            let response = ShowList.GetList.Response(list: list, error: error)
            self.presenter?.presentList(response: response)
        }
    }
}
