//
//  ShowListRouter.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 04/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ShowListRoutingLogic
{
    func routeToEditListItem(segue: UIStoryboardSegue?)
}

protocol ShowListDataPassing
{
    var dataStore: ShowListDataStore? { get }
}

class ShowListRouter: NSObject, ShowListRoutingLogic, ShowListDataPassing
{
    weak var viewController: ShowListViewController?
    var dataStore: ShowListDataStore?
    
    // MARK: Routing
    
    func routeToEditListItem(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! EditListItemViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToEditListItem(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "EditListItemViewController") as! EditListItemViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToEditListItem(source: dataStore!, destination: &destinationDS)
            navigateToEditListItem(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToEditListItem(source: ShowListViewController, destination: EditListItemViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToEditListItem(source: ShowListDataStore, destination: inout EditListItemDataStore)
    {
        let selectedIndex = viewController!.itemsTableView.indexPathForSelectedRow!
        destination.listItem = source.list.categories[selectedIndex.section].items[selectedIndex.row]
        destination.listID = source.list.id
    }
}
