//
//  ShowListPresenter.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 04/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowListPresentationLogic
{
    func presentList(response: ShowList.GetList.Response)
    func presentListUpdated(response: ShowList.UpdateListItem.Response)
    func presentListDeleted(response: ShowList.DeleteListItem.Response)
    func presentListUpdateTotal(response: ShowList.UpdateListTotal.Response)
}

class ShowListPresenter: ShowListPresentationLogic
{

    weak var viewController: ShowListDisplayLogic?
    
    let currency: String = "£"
    
    // MARK: Do something
    
    func presentList(response: ShowList.GetList.Response)
    {
        var displayedList: ShowList.DisplayedList?
        
        if let list = response.list {

            let categories = createDisplayedCategories(categories: list.categories, currency: currency)
            
            displayedList = ShowList.DisplayedList(
                id: list.id,
                name: list.name,
                categories: categories,
                oldTotalPrice: list.oldTotalPrice != nil ? list.getOldTotalPrice() : nil,
                totalPrice: list.getTotalPrice()
            )
        }
        
        let viewModel = ShowList.GetList.ViewModel(displayedList: displayedList, error: response.error)
        viewController?.displayList(viewModel: viewModel)
    }
    
    
    func presentListUpdated(response: ShowList.UpdateListItem.Response) {
        let viewModel = ShowList.UpdateListItem.ViewModel(error: response.error)
        viewController?.displayListItemUpdated(viewModel: viewModel)
    }
    
    func presentListDeleted(response: ShowList.DeleteListItem.Response) {
        let viewModel = ShowList.DeleteListItem.ViewModel(error: response.error)
        viewController?.displayListItemDeleted(viewModel: viewModel)
    }

    func presentListUpdateTotal(response: ShowList.UpdateListTotal.Response) {
        let list = response.list
        let displayedListPrice = ShowList.DisplayedListPrice(totalPrice: list.getTotalPrice(), oldTotalPrice: list.getOldTotalPrice())
        
        let viewModel = ShowList.UpdateListTotal.ViewModel(displayedPrice: displayedListPrice)
        viewController?.displayListUpdateTotal(viewModel: viewModel)
    }
}

extension ShowListPresenter {

    private func createDisplayedCategories(categories: [ListCategoryModel], currency: String) -> [ShowList.DisplayedListCategory] {
        var displayCategories: [ShowList.DisplayedListCategory] = []
        
        for category in categories {
            let items = createDisplayedItems(items: category.items, currency: currency)
            displayCategories.append(
                ShowList.DisplayedListCategory(name: category.name, items: items)
            )
        }
        
        return displayCategories
    }
    
    private func createDisplayedItems(items: [ListItemModel], currency: String) -> [ShowList.DisplayedListItem] {
        return items.map { (item: ListItemModel) in
            return ShowList.DisplayedListItem(
                name: item.name, productID: item.productID,
                quantity: item.quantity,
                totalPrice: item.getPrice(),
                tickedOff: item.tickedOff
            )
        }
    }

}
