//
//  ShowListInteractor.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 04/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowListBusinessLogic
{
    func getList(request: ShowList.GetList.Request)
    func updateListItem(request: ShowList.UpdateListItem.Request)
    func deleteListItem(request: ShowList.DeleteListItem.Request)
    
    var list: ListModel! { get set }
}

protocol ShowListDataStore
{
    var list: ListModel! { get set }
}

class ShowListInteractor: ShowListBusinessLogic, ShowListDataStore
{
    var presenter: ShowListPresentationLogic?
    
    var listWorker: ListWorker = ListWorker(listAPI: ListAPI())
    var listItemWorker: ListItemWorker = ListItemWorker(listItemAPI: ListItemAPI())
    
    var list: ListModel!
    
    func getList(request: ShowList.GetList.Request)
    {
        listWorker.getList(listID: list.id) { (list: ListModel?, error: String?) in
            
            if list != nil {
                self.list = list
            }
            
            let response = ShowList.GetList.Response(list: list, error: error)
            self.presenter?.presentList(response: response)
        }
    }
    
    func updateListItem(request: ShowList.UpdateListItem.Request){
        let listID: Int = list.id
        let productID: Int = request.productID
        let quantity: Int = request.quantity
        let tickedOff = request.tickedOff
        
        listItemWorker.updateItem(listID: listID, productID: productID, quantity: quantity, tickedOff: tickedOff) { (error: String?) in
            
        }
    }
    
    func deleteListItem(request: ShowList.DeleteListItem.Request){
        let listID: Int = list.id
        let productID: Int = request.productID
        
        listItemWorker.deleteItem(listID: listID, productID: productID) { (error: String?) in
            
        }
    }
}
