//
//  CreateListViewController.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 04/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateListDisplayLogic: AnyObject
{
    func displayListCreated(viewModel: CreateList.CreateList.ViewModel)
}

class CreateListViewController: UIViewController, CreateListDisplayLogic
{
    var interactor: CreateListBusinessLogic?
    var router: (NSObjectProtocol & CreateListRoutingLogic & CreateListDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = CreateListInteractor()
        let presenter = CreateListPresenter()
        let router = CreateListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        setupFieldDelegate()
        openKeyboardOnTextField()
        displayModelCreateButton()
    }
    
    let spinner: SpinnerViewController = SpinnerViewController()
    @IBOutlet weak var nameTextField: UITextField!
    
    @IBOutlet var createButton: UIButton!

    func createList()
    {
        let name = nameTextField.text ?? ""
        
        let request = CreateList.CreateList.Request(name: name)
        interactor?.createList(request: request)
    }
    
    func displayListCreated(viewModel: CreateList.CreateList.ViewModel)
    {
        stopLoading()
        
        if let error = viewModel.error {
            showRightBarButton()
            showError(title: "Create List Error", error: error)
        } else {
            router?.routeToShowLists(segue: nil)
        }
    }
    
    func displayModelCreateButton(){
        // Only show modally
        createButton.isHidden = !interactor!.getAddToList()
    }
    
    @IBAction func createButtonPressed(_ sender: Any) {
        submitForm()
    }
    
    func submitForm(){
        startLoading()
        dismissKeyboard()
        hideRightBarButton()
        
        createList()
    }

}

extension CreateListViewController {
    func showRightBarButton(){
        navigationItem.rightBarButtonItem?.isEnabled = true
    }
    
    func hideRightBarButton(){
        navigationItem.rightBarButtonItem?.isEnabled = false
    }
    
    func dismissKeyboard(){
        view.endEditing(true)
    }
    
    
    func openKeyboardOnTextField(){
        nameTextField.becomeFirstResponder()
    }
}

extension CreateListViewController: UITextFieldDelegate {
    
    private func setupFieldDelegate(){
        nameTextField.delegate = self
    }
    
    func textFieldShouldReturn(_ textField: UITextField) -> Bool
    {
        textField.resignFirstResponder()
        submitForm()
        return true
    }
}

extension CreateListViewController {
    func startLoading() {
        addChild(spinner)
        spinner.view.frame = view.frame
        view.addSubview(spinner.view)
        spinner.didMove(toParent: self)
    }
    
    func stopLoading(){
        spinner.willMove(toParent: nil)
        spinner.view.removeFromSuperview()
        spinner.removeFromParent()
    }
}
