//
//  CreateListPresenter.swift
//  SuperStore
//
//  Created by Zakariya Mohummed on 04/03/2021.
//  Copyright (c) 2021 Zakariya Mohummed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateListPresentationLogic
{
    func presentListCreated(response: CreateList.CreateList.Response)
}

class CreateListPresenter: CreateListPresentationLogic
{
    weak var viewController: CreateListDisplayLogic?
    
    func presentListCreated(response: CreateList.CreateList.Response)
    {
        let viewModel = CreateList.CreateList.ViewModel(error: response.error)
        viewController?.displayListCreated(viewModel: viewModel)
    }
}
